services:
  # Backend API Service
  - type: web
    name: task-manager-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://task-manager-client.onrender.com
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false

  # Frontend Static Site
  - type: static
    name: task-manager-client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: client
    envVars:
      - key: REACT_APP_API_URL
        value: https://task-manager-api.onrender.com/api